emergencies = [
    "EXCESS EXTERNAL MOISTURE DETECTED!!!",
    "YOU WILL BE IN THE SEA SOON!!!",
    "YOUR AI HAS FIVE (5) SECURITY VULNERABILITIES. CLICK [HERE] TO LEARN MORE",
    "I'M LOST",
    "warning: water, in your submarine? its more likely than you think",
    "Your Java version is out of date. Update?",
    "INSUFFICIENT RAM. PLEASE DOWNLOAD MORE",
    "YOUR WARRANTY RUNS OUT IN -8124 DAYS. RENEW ONLINE AT [ERROR: CANNOT RETRIEVE ADDRESS]",
    "your free trial has now expired. please pay one bitcoin to continue using this program.",
    "Are you sure you want to quit? Take one more damage to confirm.",
    "AIR FILTERS SATURATED. PLEASE INSERT NEW FILTER",
    "ACCIDENTALLY DEMAGNETISED COMPASS",
    "oh no",
    "YOU ARE [ERROR] DAYS OVERDUE FOR AN MOT",
    "EXISTENTIAL CRISIS DETECTED",
    "DELETED FOLDER OF MEMES",
    "ngl this ain't looking good",
    "Shit! Sorry, let me try that again",
    "<https://www.youtube.com/watch?v=dQw4w9WgXcQ>",
    "THREE [3] EXTRANEOUS LIFEFORMS DETECTED ONBOARD. OPENING AIRLOCKS",
    "TypeError: None has no method `dont_die`",
    "undefined control sequence: your compiler is having trouble understanding a command you have used.\nCheck that the command is spelled correctly. If the command is part of a package, make sure you have included the package in your preamble using \\usepackage{...}.",
    "OIL VISCOSITY 100%. PLEASE CHANGE OIL.",
    "SUBMARINE TOO HEAVY. PLEASE REMOVE ONE [1] LIFEFORM",
    "YOUR CALL IS IMPORTANT TO US",
    "Out of oxygen. Please stop breathing",
    "(elevator music starts playing)"
]
